services:
  postgres:
    image: postgres:14.10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Pg123 
      - POSTGRES_USER=kubenews 
      - POSTGRES_DB=kubenews
    volumes:
     #Bind mount
     # - /home/schelbauer/aula/volumes/postgres_vol:/var/lib/postgresql/data
      - postgres_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net

  kube_news:
    image: schelbauer/kube-news:v2
    ports:
      - 8080:8080
    networks:
      - kube_news_net
    environment:
      - DB_DATABASE=kubenews
      - DB_USERNAME=kubenews
      - DB_PASSWORD=Pg123
      - DB_HOST=postgres
    depends_on:
      - postgres
volumes:
  postgres_docker_vol:
networks:
  kube_news_net:
    driver: bridge
